#!/usr/bin/env perl
use strict;
use warnings;

use LWP::Simple;
use Text::CSV;

my $filename = 'australian_postcodes.csv';
my $csv = Text::CSV->new({ sep_char => ',' });
my %seen;

open(my $fh, '<:encoding(UTF-8)', $filename)
    or die "Could not open file '$filename' $!";
 
while (my $line = <$fh>) {
    if (!$csv->parse($line)) {
        warn "Line could not be parsed: $line\n";
        next;
    }

    my @fields = $csv->fields();
    next if (exists($seen{"$fields[1] $fields[2]"}));

    print "UPDATE `LOCALITY` ".
        "JOIN `STATE` USING (state_pid) ".
        "SET primary_postcode = '$fields[0]' ".
        "WHERE locality_name = \"$fields[1]\" ".
        "AND state_abbreviation = '$fields[2]';\n";

    $seen{"$fields[1] $fields[2]"} = 1;
}
